### ISSUE TITLE
Automatic error and stats sending

### ISSUE THREAD

**Issue by HR** [codexa/firetext#113]
Send any errors automatically to support@codexa.org with all info of error (I.e. Firetext version, Firefox OS/Browser version, time&date Client ID, etc). Now for the stats part we are using Google Analytics mainly so I'll add that. User shouldn't see the exact details of what went wrong in the execution and only need to be given instruction such as "Try again later".

**Comment by ferndot** [comment]
I don't think that we should send them to the email because that might flood us with minor errors.  It should send a http POST request to firetext.codexa.org/stats, and admins should be able to access that page and see a list of errors with debug info.  In the settings section, you should be able to check a box and enter an email so that admins can contact you for help on critical errors.

The second part I totally agree with!

**Comment by HR** [comment]
Yup but then we have to create a system yo sort this out, or is their any framework that exist?

**Comment by HR** [comment]
this will be part of logging (#71)
