### ISSUE TITLE
updateDocLists searching wrong folder for FileSystem

### ISSUE THREAD

**Issue by jackd1** [codexa/firetext#153]
The updateDocLists function searches the root directory for files.  However, for the FileSystem api, for browsers that support it, we creates documents in the /Documents directory to mimic the behavior of Firefox OS.  Is updateDocLists supposed to be searching the root directory, and if so what would you like me to do for the FileSystem api.

**Comment by ferndot** [comment]
It is supposed to search the entire filesystem (on mobile devices).  Desktop filesystems are way too big to enumerate :D.  Does it sound good to have some sort of upload link instead of enumerating every file on Desktops?  

For mobiles with the FileSystem API, you can choose to do /Documents, or just enumerate the root directory.  I think that the latter is better.

**Comment by jackd1** [comment]
Ok, I'll set up enumerate to search the entire root directory.  About desktop, we generally won't have direct access to the actual filesystem.  We can just allow the user to upload files and load them into whatever file storage we are using (FileSystem, dropbox, drive).

**Comment by ferndot** [comment]
Yep!

**Comment by ferndot** [comment]
Awesome, I just have one question.  Does this function get all files in the filesystem, or just in the root directory?

**Comment by jackd1** [comment]
It gets all of the files in the filesystem if it is passed the root directory.

**Comment by ferndot** [comment]
Okay, great!
