### ISSUE TITLE
Red header

### ISSUE THREAD

**Issue by HR** [codexa/firetext#32]
As our logo mostly contains red and "fire" is red, what about changing the headers to a red color?

**Comment by ferndot** [comment]
I don't know, there is no red style so we would have to do our own.  If you want to work on this, that would be fine.  Just modify main.css.

**Comment by HR** [comment]
What do you think about this: https://www.dropbox.com/s/68rksjdydb3ngfu/ftred.PNG?v=0rc-s

**Comment by ferndot** [comment]
Looks ok to me, @Logi0, @Graeme22 what do you guys think?

**Comment by logan-r** [comment]
I prefer the regular orange header, since it fits in with the rest of the Firefox OS apps.
From https://blog.mozilla.org/ux/2012/09/mozcamp-warsaw-design-principles-behind-firefox-os-ux/:
- phone related: green
- media related: blue
- productivity related: orange
- settings and utilities: gray

Also, I've always associated orange with fire (and Firefox).
But if both you (@HRanDEV) and @Joshua-S want it, then I'm fine with it.

**Comment by ferndot** [comment]
I would prefer to stick to platform defaults at least right now.
